Repository import-antML/ant-hology, pull requests merged in 2020-11, with the labels that each got.

#4 PR: add poke plotly
  신주연/Pokedex_Ver3.csv
  신주연/Pokemon.csv
  신주연/combats.csv
  신주연/poke.ipynb
  신주연/pokemon_2.csv
  신주연/pokemon_kr.csv
Labels: enhancement

#5 upload file_20201110
  김미림/1. Plotly 스터디/20200827_plotly.ipynb
  김미림/1. Plotly 스터디/20201103_plotly dash.ipynb
  김미림/1. Plotly 스터디/plotly_express-0.4.1-py2.py3-none-any.whl
  김미림/1. Plotly 스터디/pokemon.csv
  김미림/2. Git, Github 스터디/20201110_Github 내용.txt
  김미림/20200909_plotly.ipynb
  김미림/PersonalMemo.md
  김미림/plotly_express-0.4.1-py2.py3-none-any.whl
  김미림/pokemon.csv
Labels: good first issue

#6 <add>: 풀 리퀘스트 연습용 파일 추가
  ksk/git_study/for_pull_request.txt
  ksk/poke/Pipfile
  ksk/poke/Pipfile.lock
  ksk/poke/src/mission 1.ipynb
Labels: enhancement

#7 20201110_lsh_pull-request
  pull_request_readme.txt
Labels: documentation

#9 Add 201110_git.md
  엄수림/20201110_git.md
Labels: documentation
